#!/bin/sh
mkdir -p $HOME/.local/
mkdir -p $HOME/.local/share/
mkdir -p $HOME/.local/share/mysh/
mkdir -p $HOME/.local/share/mysh/hosts

touch $HOME/.local/share/mysh/completion
echo "remotes: {}" > $HOME/.local/share/mysh/remotes.yaml
echo "namespaces: {}" > $HOME/.local/share/mysh/global.yaml
