#!/usr/bin/env python
import os
import sys

core_path = '/usr/local/bin/mysh_core'
stream = os.popen(core_path + ' ' + ' '.join(sys.argv[1:]))
output = stream.read()
if ('ssh ' in output):
    os.system(output)
else:
    print(output.rstrip("\n"))
